name: Metrics
on:
  schedule: [{cron: "*/30 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          # Options
          user: juruo888
          template: classic
          base: header, activity, community, metadata
          config_timezone: Asia/Shanghai
          plugin_followup: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_stargazers: yes
          plugin_pagespeed: no
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_screenshot: no
          plugin_pagespeed_url: .user.website
          plugin_people_user: .github.user
          plugin_contributors: yes
          plugin_contributors_base: ""
          plugin_contributors_head: master
          plugin_contributors_contributions: yes
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes
          plugin_achievements_limit: 0
          plugin_lines: yes
          plugin_notable: yes
          plugin_notable_filter: stars:>0
          plugin_notable_repositories: yes
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_activity_filter: all